version: '3'
services:
  ldap:
    image: ldap
    container_name: ldap
    build:
      context: ldap
    ports:
      - '389:389'
    environment:
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "password"
  idp:
    image: idp 
    container_name: idp
    build:
      context: idp
    ports:
      - 443:8443
    volumes:
      - ./idp/conf.mnt:/opt/shibboleth-idp/conf
      - ./idp/logs:/opt/shibboleth-idp/logs
  sp:
    image: sp
    container_name: sp
    build:
      context: sp
    ports:
      - 10443:10443
    volumes:
      - ./sp/app:/var/www/html/secure
      - ./sp/shibboleth:/var/log/shibboleth
      - ./sp/httpd:/var/log/httpd
