version: '3'
services:
  ldap:
    image: ldap
    container_name: ldap
    build:
      context: ldap
    ports:
      - '389:389'
    environment:
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "password"
  idp:
    image: idp
    container_name: idp
    build:
      context: idp
    depends_on:
      - ldap
    ports:
      - 443:8443
      - 80:8080
    environment:
      LDAP_HOST: "ldap"
  sp:
    image: sp
    container_name: sp
    build:
      context: sp
    depends_on:
      - idp
    ports:
      - 10443:443
